import React from 'react'


export const metadata = {
  title: "Cockapo-About",
  description: "Generated by create next app",
};
const about = () => {
  return (
    <div>
      <h1>About</h1>
    </div>
  )
}

export default about
