import "./globals.css";
import { Inter, Lalezar } from "next/font/google";
import Nav from "@/components/Nav/nav";
import Footer from "@/components/Footer/footer";
import { ThemContext, ThemProveder } from "@/context/themContext";

const inter = Inter({ subsets: ["latin"] });
const lalezar = Lalezar({ subsets: ["arabic"],weight:['400']});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemProveder>
        <div className="container">
          <Nav/>

          {children}
          
          <Footer />
        
        </div>

        </ThemProveder>
        
      </body>
    </html>
  );
}
